# -*- coding: utf-8 -*-
"""TitanicEDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cNRNX9vhu9uVD3rzdGfN126ZIEfHBIdH
"""

import pandas as pd

file_path = '/content/titanic.csv'

titanic_data = pd.read_csv(file_path)

titanic_data.head()

missing_values = titanic_data.isnull().sum()

missing_values

median_age = titanic_data['Age'].median()

titanic_data['Age'].fillna(median_age, inplace=True)

mode_embarked = titanic_data['Embarked'].mode()[0]

titanic_data['Embarked'].fillna(mode_embarked, inplace=True)

missing_values_after_cleaning = titanic_data[['Age', 'Embarked']].isnull().sum()

missing_values_after_cleaning

import matplotlib.pyplot as plt

import seaborn as sns

sns.set(style="whitegrid")

plt.figure(figsize=(12, 6))

sns.histplot(titanic_data['Age'], kde=True, bins=30)

plt.title('Age Distribution of Titanic Passengers')

plt.xlabel('Age')

plt.ylabel('Frequency')

plt.show()

plt.figure(figsize=(12, 6))

sns.histplot(titanic_data[titanic_data['Survived'] == 1]['Age'], kde=True, color='blue', bins=30, label='Survived')

sns.histplot(titanic_data[titanic_data['Survived'] == 0]['Age'], kde=True, color='red', bins=30, label='Not Survived')

plt.title('Survival Rate by Age')

plt.xlabel('Age')

plt.ylabel('Frequency')

plt.legend()

plt.show()

plt.figure(figsize=(12, 6))

sns.histplot(titanic_data[titanic_data['Survived'] == 1]['Age'], kde=True, color='blue', bins=30, label='Survived')

sns.histplot(titanic_data[titanic_data['Survived'] == 0]['Age'], kde=True, color='red', bins=30, label='Not Survived')

plt.title('Survival Rate by Age')

plt.xlabel('Age')

plt.ylabel('Frequency')

plt.legend()

plt.show()